### ISSUE TITLE
filter matching

### ISSUE THREAD

**Issue by elbucho** [jusmark123/stocks-api#4]
Hey man - looks like the filter matching behavior is subtractive, not additive.  When I search for "mi" on both name and ticker, I only get two results, even though if I were to do a union in the database, I'd get 155 rows back.  My changes are on the front-end branch (api_filters/tickers.yml & api_resources/ticker.yml).

`select id, ticker, name from ticker where ticker like '%mi%' union select id, ticker, name from ticker where name like '%mi%' group by id;`

vs

http://localhost:8080/api/stocks/v1/tickers?itemsperpage=50&ticker=Mi&name=Mi

**Comment by elbucho** [comment]
You know what - instead of fucking with it and creating some bespoke workaround, I think I'm just going to do two different searches on the back-end, and paginate the data at the front end.  It's not ideal, but it should work.

**Comment by jusmark123** [comment]
I have a fix for it, will get it tagged and pushed up today to this branch for testing

**Comment by jusmark123** [comment]
Added to https://github.com/jusmark123/stocks-api/tree/front-end branch will link to pull request when ready to merge
